### PR TITLE
Update alloy.tmLanguage

### PR DESCRIPTION
**Pull request by pkriens**
This is an update for the upcoming Alloy 6 release which will be based on Electrum. We would appreciate it if you could take these changes.

### CODE REVIEW

**Comment by pkriens** [comment]
ping?

**Comment by macekond** [comment]
Hello @pkriens, as obvious I do not have time/reason to maintain this repository. I can transfer the ownership to you if you want to keep it up to date. Is it OK?

**Comment by pkriens** [comment]
Could you make me a committer on this repo? I think the reason is asked you that people (Github?) uses this as the source for the Alloy language. If we change the owner it will be hard to get this all correct again.

**Comment by pkriens** [comment]
Thanks! Appreciate the confidence

**Pull request merged**
